# Site settings
title: Stuti Thapa
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stutithapa.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Stuti Thapa
user_description: Graduate student at Purdue University's Industrial organizational Psychology program. I'm interested in well-being, emotion dynamics, and the effects of time. 
user_title: Graduate Student
email: thapastuti7@gmail.com
# twitter_username: lorem_ipsum
github_username:  stutithapa
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
